name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  PROJECT_ID: sistem-informasi-konveksi # TODO: update Google Cloud project id
  GAR_LOCATION: asia-southeast2 # TODO: update Artifact Registry location
  REPOSITORY: registry-sistem-informasi-konveksi # TODO: update Artifact Registry repository name
  SERVICE: go-sistem-informasi-konveksi # TODO: update Cloud Run service name
  REGION: asia-southeast2 # TODO: update Cloud Run service region
  ENVIRONMENT: PRODUCTION # TODO: update Status Application (PRODUCTION/DEVELOPMENT)
  VERSION_SECRET_MANAGER: 1 # TODO: update Version Secret Manager

jobs:
  build-deploy-gcloud:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Push to Registry 
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ steps.vars.outputs.sha_short }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ steps.vars.outputs.sha_short }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.GAR_LOCATION }}
          flags: "--service-account=${{secrets.SERVICE_ACCOUNT}}\
            --allow-unauthenticated\ 
            --set-secrets=DB_Username=DB_Username:${{ env.VERSION_SECRET_MANAGER }},\
              DB_Password=DB_Password:${{ env.VERSION_SECRET_MANAGER }},\
              DB_Port=DB_Port:${{ env.VERSION_SECRET_MANAGER }},\
              DB_Host=DB_Host:${{ env.VERSION_SECRET_MANAGER }},\
              DB_Name=DB_Name:${{ env.VERSION_SECRET_MANAGER }},\
              JWT_Secret=JWT_Secret:${{ env.VERSION_SECRET_MANAGER }},\
              JWT_Secret_Refresh=JWT_Secret_Refresh:${{ env.VERSION_SECRET_MANAGER }},\
              BUCKET_NAME=BUCKET_NAME:${{ env.VERSION_SECRET_MANAGER }}"
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ steps.vars.outputs.sha_short }}
          # NOTE: You can also set env variables here:
          env_vars: |
            ENVIRONMENT=${{ env.ENVIRONMENT }}
            PROJECT_ID=${{ env.PROJECT_ID }}
            ALLOW_ORIGINS=${{ secrets.ALLOW_ORIGINS }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_TOKEN=${{ secrets.JWT_TOKEN }}
            JWT_REFTOKEN=${{ secrets.JWT_REFTOKEN }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}